name: Build and Upload Conda

on:
  push:
    branches:
      - main
  # release:
    # types: [published]

jobs:
  container:
    image: continuumio/miniconda3
    

# jobs:
  # publish:
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v1
    # - name: publish-to-conda
      # uses: MichaelsJP/conda-package-publish-action@v1.0.0
      # with:
        # subDir: '.conda'
        # AnacondaToken: ${{ secrets.USERNAME_TOKEN }}
        # platforms: 'all'
        # override: true
        # dry_run: true
